name: animated_education
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  shared_preferences: ^2.0.16
  get: ^4.6.3
  webview_flutter: ^3.0.4
  webview_flutter_web: ^0.1.0+4
  webviewx_plus: ^0.3.2
  code_text_field: ^1.1.0
#  flutter_echarts: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/user.png



fonts:
  - family: Questrial
    fonts:
      - asset: fonts/Questrial-Regular.ttf
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.ttf
  - family: Quantico
#    fonts:
#      - asset: fonts/Quantico-Regular.otf

    fonts:
      - family: SourceCode
        fonts:
          - asset: assets/fonts/sourceCode/SourceCodePro-Black.ttf
            weight: 900
          - asset: assets/fonts/sourceCode/SourceCodePro-BlackItalic.ttf
            style: italic
            weight: 900
          - asset: assets/fonts/sourceCode/SourceCodePro-Bold.ttf
            weight: 700
          - asset: assets/fonts/sourceCode/SourceCodePro-BoldItalic.ttf
            style: italic
            weight: 700
          - asset: assets/fonts/sourceCode/SourceCodePro-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/sourceCode/SourceCodePro-SemiBoldItalic.ttf
            style: italic
            weight: 600
          - asset: assets/fonts/sourceCode/SourceCodePro-Medium.ttf
            weight: 500
          - asset: assets/fonts/sourceCode/SourceCodePro-MediumItalic.ttf
            style: italic
            weight: 500
          - asset: assets/fonts/sourceCode/SourceCodePro-Regular.ttf
            weight: 400
          - asset: assets/fonts/sourceCode/SourceCodePro-Italic.ttf
            style: italic
            weight: 400
          - asset: assets/fonts/sourceCode/SourceCodePro-Light.ttf
            weight: 300
          - asset: assets/fonts/sourceCode/SourceCodePro-LightItalic.ttf
            style: italic
            weight: 300
          - asset: assets/fonts/sourceCode/SourceCodePro-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/sourceCode/SourceCodePro-ExtraLightItalic.ttf
            style: italic
            weight: 200


